"""Persistent, source-attributed prompt/video style library."""

from __future__ import annotations

import copy
import json
import os
import re
import subprocess
import threading
import time
import uuid
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Any


MINIMAX_H3_1K_SOURCE = {
    "id": "huggingface:ostris/minimax_h3_1k",
    "type": "huggingface_dataset",
    "author": "ostris",
    "name": "MiniMax H3 - 1K",
    "url": "https://huggingface.co/datasets/ostris/minimax_h3_1k",
    "repoId": "ostris/minimax_h3_1k",
    "modelFamily": "minimax",
    "collection": "MiniMax H3 1K",
    "license": None,
    "licenseNotice": "No license is specified in the dataset card.",
    "description": (
        "1,000 MiniMax H3 capability samples at 768-base resolution, "
        "generated by the source author with 30 steps."
    ),
    "expectedStyles": 1000,
    "expectedBytes": 1_432_969_644,
}

_STYLE_ID = re.compile(r"minimax-h3-1k-(\d{6})$")


def _atomic_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{uuid.uuid4().hex}.tmp")
    temporary.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    os.replace(temporary, path)


def _directory_stats(directory: Path) -> tuple[int, int]:
    files = 0
    size = 0
    if not directory.is_dir():
        return files, size
    for entry in directory.iterdir():
        try:
            if entry.is_file() and entry.suffix.lower() in {".mp4", ".txt"}:
                files += 1
                size += entry.stat().st_size
        except OSError:
            continue
    return files, size


class StyleLibrary:
    """Own style manifests, media, import jobs and deletion tombstones."""

    def __init__(self, root: str | os.PathLike[str]) -> None:
        self.root = Path(root)
        self.source_root = self.root / "minimax" / "ostris-minimax_h3_1k"
        self.raw_dir = self.source_root / "raw"
        self.preview_dir = self.source_root / "previews"
        self.manifest_path = self.source_root / "manifest.json"
        self.job_path = self.source_root / "import-job.json"
        self._lock = threading.RLock()
        self._jobs: dict[str, dict[str, Any]] = {}
        self._active_job_id: str | None = None
        self._recover_job()

    def _recover_job(self) -> None:
        if not self.job_path.is_file():
            return
        try:
            job = json.loads(self.job_path.read_text(encoding="utf-8"))
        except (OSError, ValueError, json.JSONDecodeError):
            return
        if not isinstance(job, dict) or not job.get("jobId"):
            return
        if job.get("status") in {"queued", "running"}:
            job.update({
                "status": "interrupted",
                "message": "Import interrupted; press download again to resume.",
                "updatedAt": time.time(),
                "finishedAt": time.time(),
            })
            _atomic_json(self.job_path, job)
        self._jobs[str(job["jobId"])] = job

    def _manifest(self) -> dict[str, Any]:
        if not self.manifest_path.is_file():
            return {
                "version": 1,
                "source": copy.deepcopy(MINIMAX_H3_1K_SOURCE),
                "styles": [],
                "deletedIds": [],
                "updatedAt": None,
            }
        try:
            payload = json.loads(self.manifest_path.read_text(encoding="utf-8"))
        except (OSError, ValueError, json.JSONDecodeError):
            return {
                "version": 1,
                "source": copy.deepcopy(MINIMAX_H3_1K_SOURCE),
                "styles": [],
                "deletedIds": [],
                "updatedAt": None,
            }
        return payload if isinstance(payload, dict) else {}

    def source_status(self) -> list[dict[str, Any]]:
        with self._lock:
            manifest = self._manifest()
            deleted = set(manifest.get("deletedIds") or [])
            styles = [
                item for item in manifest.get("styles", [])
                if isinstance(item, dict) and item.get("id") not in deleted
            ]
            files, downloaded_bytes = _directory_stats(self.raw_dir)
            active = self._jobs.get(self._active_job_id or "")
            source = copy.deepcopy(MINIMAX_H3_1K_SOURCE)
            source.update({
                "revision": (manifest.get("source") or {}).get("revision"),
                "lastModified": (manifest.get("source") or {}).get("lastModified"),
                "installed": bool(styles),
                "styleCount": len(styles),
                "downloadedFiles": files,
                "downloadedBytes": downloaded_bytes,
                "activeJob": copy.deepcopy(active) if active else None,
            })
            return [source]

    def list_styles(
        self,
        *,
        model_family: str = "minimax",
        source_id: str = "",
        collection: str = "",
        group: str = "",
        query: str = "",
        sort: str = "source_order",
        offset: int = 0,
        limit: int = 60,
    ) -> dict[str, Any]:
        with self._lock:
            manifest = self._manifest()
        deleted = set(manifest.get("deletedIds") or [])
        items = [
            copy.deepcopy(item)
            for item in manifest.get("styles", [])
            if isinstance(item, dict) and item.get("id") not in deleted
        ]
        if model_family:
            items = [item for item in items if item.get("modelFamily") == model_family]
        if source_id:
            items = [item for item in items if (item.get("source") or {}).get("id") == source_id]
        if collection:
            items = [item for item in items if item.get("collection") == collection]
        if group:
            items = [item for item in items if item.get("group") == group]
        needle = query.strip().casefold()
        if needle:
            items = [
                item for item in items
                if needle in str(item.get("prompt") or "").casefold()
                or needle in str(item.get("title") or "").casefold()
                or any(needle in str(tag).casefold() for tag in item.get("tags") or [])
            ]
        if sort == "prompt_asc":
            items.sort(key=lambda item: str(item.get("prompt") or "").casefold())
        elif sort == "prompt_desc":
            items.sort(key=lambda item: str(item.get("prompt") or "").casefold(), reverse=True)
        elif sort == "newest":
            items.sort(key=lambda item: float(item.get("importedAt") or 0), reverse=True)
        elif sort == "oldest":
            items.sort(key=lambda item: float(item.get("importedAt") or 0))
        else:
            items.sort(key=lambda item: int(item.get("sourceOrder") or 0))
        total = len(items)
        offset = max(0, int(offset))
        limit = min(200, max(1, int(limit)))
        page = items[offset:offset + limit]
        for item in page:
            style_id = str(item["id"])
            item["previewUrl"] = f"/api/v1/style-library/styles/{style_id}/preview"
            item["videoUrl"] = f"/api/v1/style-library/styles/{style_id}/video"
        facets = {
            "sources": sorted({
                str((item.get("source") or {}).get("id") or "")
                for item in items if (item.get("source") or {}).get("id")
            }),
            "collections": sorted({str(item.get("collection")) for item in items if item.get("collection")}),
            "groups": sorted({str(item.get("group")) for item in items if item.get("group")}),
        }
        return {"styles": page, "total": total, "offset": offset, "limit": limit, "facets": facets}

    def start_minimax_import(self) -> dict[str, Any]:
        with self._lock:
            if self._active_job_id:
                active = self._jobs.get(self._active_job_id)
                if active and active.get("status") in {"queued", "running"}:
                    return copy.deepcopy(active)
            job_id = f"style-import-{uuid.uuid4().hex[:12]}"
            job = {
                "jobId": job_id,
                "status": "queued",
                "stage": "queued",
                "current": 0,
                "total": int(MINIMAX_H3_1K_SOURCE["expectedStyles"]),
                "message": "Preparing MiniMax H3 style download…",
                "downloadedBytes": 0,
                "expectedBytes": int(MINIMAX_H3_1K_SOURCE["expectedBytes"]),
                "error": None,
                "createdAt": time.time(),
                "updatedAt": time.time(),
                "finishedAt": None,
                "source": copy.deepcopy(MINIMAX_H3_1K_SOURCE),
            }
            self._jobs[job_id] = job
            self._active_job_id = job_id
            _atomic_json(self.job_path, job)
            thread = threading.Thread(
                target=self._run_minimax_import,
                args=(job_id,),
                name=f"style-import-{job_id[-6:]}",
                daemon=True,
            )
            thread.start()
            return copy.deepcopy(job)

    def import_status(self, job_id: str) -> dict[str, Any] | None:
        with self._lock:
            job = self._jobs.get(job_id)
            return copy.deepcopy(job) if job else None

    def _update_job(self, job_id: str, *, persist: bool = True, **patch: Any) -> None:
        with self._lock:
            job = self._jobs.get(job_id)
            if not job:
                return
            job.update(copy.deepcopy(patch))
            job["updatedAt"] = time.time()
            snapshot = copy.deepcopy(job)
        if persist:
            _atomic_json(self.job_path, snapshot)

    def _monitor_download(self, job_id: str, stop: threading.Event) -> None:
        while not stop.wait(1.0):
            files, downloaded_bytes = _directory_stats(self.raw_dir)
            pairs = min(1000, files // 2)
            self._update_job(
                job_id,
                persist=False,
                current=pairs,
                downloadedBytes=downloaded_bytes,
                message=f"Downloading style media… {pairs}/1000",
            )

    def _run_minimax_import(self, job_id: str) -> None:
        monitor_stop = threading.Event()
        monitor: threading.Thread | None = None
        try:
            self.raw_dir.mkdir(parents=True, exist_ok=True)
            self.preview_dir.mkdir(parents=True, exist_ok=True)
            existing = self._manifest()
            deleted_ids = set(existing.get("deletedIds") or [])
            ignored: list[str] = []
            for style_id in deleted_ids:
                match = _STYLE_ID.fullmatch(str(style_id))
                if match:
                    ignored.extend([f"{match.group(1)}.mp4", f"{match.group(1)}.txt"])

            self._update_job(
                job_id,
                status="running",
                stage="downloading",
                message="Downloading 1,000 prompts and videos from Hugging Face…",
            )
            monitor = threading.Thread(
                target=self._monitor_download,
                args=(job_id, monitor_stop),
                name=f"style-progress-{job_id[-6:]}",
                daemon=True,
            )
            monitor.start()
            from huggingface_hub import HfApi, snapshot_download

            info = HfApi().dataset_info(str(MINIMAX_H3_1K_SOURCE["repoId"]))
            snapshot_download(
                repo_id=str(MINIMAX_H3_1K_SOURCE["repoId"]),
                repo_type="dataset",
                revision=info.sha,
                local_dir=str(self.raw_dir),
                allow_patterns=["*.mp4", "*.txt", "README.md"],
                ignore_patterns=ignored or None,
                max_workers=4,
            )
            monitor_stop.set()
            if monitor:
                monitor.join(timeout=3)
            files, downloaded_bytes = _directory_stats(self.raw_dir)
            self._update_job(
                job_id,
                stage="indexing",
                current=0,
                downloadedBytes=downloaded_bytes,
                message="Indexing prompts and source metadata…",
            )

            imported_at = time.time()
            source = copy.deepcopy(MINIMAX_H3_1K_SOURCE)
            source.update({
                "revision": info.sha,
                "lastModified": info.last_modified.isoformat() if info.last_modified else None,
            })
            styles: list[dict[str, Any]] = []
            for number in range(1, 1001):
                sample = f"{number:06d}"
                style_id = f"minimax-h3-1k-{sample}"
                if style_id in deleted_ids:
                    continue
                prompt_path = self.raw_dir / f"{sample}.txt"
                video_path = self.raw_dir / f"{sample}.mp4"
                if not prompt_path.is_file() or not video_path.is_file():
                    raise RuntimeError(f"Dataset sample {sample} is incomplete")
                prompt = prompt_path.read_text(encoding="utf-8").strip()
                styles.append({
                    "id": style_id,
                    "modelFamily": "minimax",
                    "title": f"MiniMax H3 sample {sample}",
                    "prompt": prompt,
                    "collection": str(source["collection"]),
                    "group": "Source dataset",
                    "tags": ["minimax-h3", "video", "reference-dataset"],
                    "sourceOrder": number,
                    "sourceFilename": f"{sample}.txt",
                    "videoFilename": f"{sample}.mp4",
                    "source": copy.deepcopy(source),
                    "importedAt": imported_at,
                })
                if number % 50 == 0:
                    self._update_job(
                        job_id,
                        persist=False,
                        current=number,
                        message=f"Indexing prompts… {number}/1000",
                    )
            manifest = {
                "version": 1,
                "source": source,
                "styles": styles,
                "deletedIds": sorted(deleted_ids),
                "updatedAt": time.time(),
            }
            _atomic_json(self.manifest_path, manifest)

            self._update_job(
                job_id,
                stage="previews",
                current=0,
                total=len(styles),
                message="Creating lightweight previews…",
            )
            completed = 0
            preview_failures: list[str] = []
            with ThreadPoolExecutor(max_workers=2) as pool:
                futures = {
                    pool.submit(self._ensure_preview_for, item): item["id"]
                    for item in styles
                }
                for future in as_completed(futures):
                    style_id = futures[future]
                    try:
                        future.result()
                    except Exception as exc:
                        preview_failures.append(f"{style_id}: {exc}")
                    completed += 1
                    if completed % 10 == 0 or completed == len(styles):
                        self._update_job(
                            job_id,
                            persist=completed % 50 == 0 or completed == len(styles),
                            current=completed,
                            previewFailures=len(preview_failures),
                            message=f"Creating lightweight previews… {completed}/{len(styles)}",
                        )
            warning = None
            if preview_failures:
                warning = (
                    f"{len(preview_failures)} previews could not be created; "
                    "their videos and prompts are still available."
                )
            self._update_job(
                job_id,
                status="completed",
                stage="completed",
                current=len(styles),
                total=len(styles),
                downloadedBytes=downloaded_bytes,
                previewFailures=len(preview_failures),
                warning=warning,
                finishedAt=time.time(),
                message=(
                    f"Imported {len(styles)} MiniMax H3 styles."
                    if not warning else f"Imported {len(styles)} styles with {warning}"
                ),
            )
        except Exception as exc:
            monitor_stop.set()
            if monitor:
                monitor.join(timeout=3)
            self._update_job(
                job_id,
                status="failed",
                stage="failed",
                error=str(exc),
                finishedAt=time.time(),
                message=f"Style import failed: {exc}",
            )
        finally:
            with self._lock:
                if self._active_job_id == job_id:
                    self._active_job_id = None

    def _style_record(self, style_id: str) -> dict[str, Any]:
        if not _STYLE_ID.fullmatch(style_id):
            raise KeyError(style_id)
        manifest = self._manifest()
        deleted = set(manifest.get("deletedIds") or [])
        if style_id in deleted:
            raise KeyError(style_id)
        record = next((
            item for item in manifest.get("styles", [])
            if isinstance(item, dict) and item.get("id") == style_id
        ), None)
        if not record:
            raise KeyError(style_id)
        return record

    def _ensure_preview_for(self, record: dict[str, Any]) -> Path:
        style_id = str(record["id"])
        destination = self.preview_dir / f"{style_id}.jpg"
        if destination.is_file() and destination.stat().st_size > 0:
            return destination
        source = self.raw_dir / str(record["videoFilename"])
        if not source.is_file():
            raise FileNotFoundError(source)
        temporary = destination.with_name(f".{destination.name}.{uuid.uuid4().hex}.tmp.jpg")
        error = "FFmpeg preview failed"
        for seek_args in (("-ss", "0.1"), ()):
            command = [
                os.environ.get("FFMPEG_BINARY", "ffmpeg"),
                "-v", "error", "-y", *seek_args, "-i", str(source),
                "-map", "0:v:0", "-frames:v", "1",
                "-vf", "scale=320:180:force_original_aspect_ratio=decrease,pad=320:180:(ow-iw)/2:(oh-ih)/2:color=black",
                "-q:v", "6", str(temporary),
            ]
            result = subprocess.run(
                command,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                timeout=90,
                check=False,
            )
            if result.returncode == 0 and temporary.is_file() and temporary.stat().st_size > 0:
                os.replace(temporary, destination)
                return destination
            error = (result.stderr or error)[-800:]
            try:
                temporary.unlink(missing_ok=True)
            except OSError:
                pass
        raise RuntimeError(error)

    def preview_path(self, style_id: str) -> Path:
        with self._lock:
            record = self._style_record(style_id)
        return self._ensure_preview_for(record)

    def video_path(self, style_id: str) -> Path:
        with self._lock:
            record = self._style_record(style_id)
        path = self.raw_dir / str(record["videoFilename"])
        if not path.is_file():
            raise FileNotFoundError(path)
        return path

    def delete_style(self, style_id: str) -> dict[str, Any]:
        with self._lock:
            record = self._style_record(style_id)
            manifest = self._manifest()
            deleted = set(manifest.get("deletedIds") or [])
            deleted.add(style_id)
            manifest["deletedIds"] = sorted(deleted)
            manifest["updatedAt"] = time.time()
            _atomic_json(self.manifest_path, manifest)
            paths = [
                self.raw_dir / str(record.get("sourceFilename") or ""),
                self.raw_dir / str(record.get("videoFilename") or ""),
                self.preview_dir / f"{style_id}.jpg",
            ]
        removed = []
        for path in paths:
            try:
                if path.is_file():
                    path.unlink()
                    removed.append(path.name)
            except OSError:
                continue
        return {"id": style_id, "deleted": True, "removedFiles": removed}
