import type { AgentAction } from './agentActions'

/**
 * Exhaustive runtime manifest for the AgentAction discriminated union.
 *
 * Keep this list separate from the capability registry so tests can prove that
 * every action exposed by the LLM schema is backed by the common command
 * contract. The type assertion below deliberately fails compilation when a new
 * AgentAction is added without being declared here.
 */
export const AGENT_ACTION_TYPES = [
  'open_tab',
  'open_story_section',
  'open_series_section',
  'prepare_video',
  'prepare_programmatic_video',
  'prepare_image',
  'prepare_audio',
  'download_model',
  'queue_sfx_pack',
  'prepare_3d',
  'start_generation',
  'create_story',
  'update_story',
  'generate_story_section',
  'apply_story_proposal',
  'approve_story_section',
  'approve_story_visuals',
  'generate_story_visuals',
  'stage_story_comic',
  'stage_story_video',
  'configure_story_song',
  'generate_story_song',
  'stage_story_music_video',
  'start_director_production',
  'create_series_episode',
  'update_series_episode',
  'generate_series_plan',
  'apply_series_plan',
  'render_series_shots',
  'review_series_attempts',
  'assemble_series_episode',
  'commit_series_canon',
  'open_3d_scene',
  'save_3d_scene',
  'export_3d_scene',
  'apply_3d_rhythm',
  'create_rhythmic_3d_video',
  'create_3d_scene',
  'set_3d_scene_properties',
  'add_3d_scene_layer',
  'update_3d_scene_layer',
  'remove_3d_scene_layer',
  'attach_3d_scene_audio',
  'analyze_3d_scene_audio',
  'apply_3d_choreography',
  'create_comic',
  'generate_comic',
  'generate_comic_panel',
  'attach_studio_references',
  'configure_studio_loras',
  'remove_background',
  'inspect_queue',
  'cancel_task',
  'resume_task',
  'retry_task',
  'select_workspace',
  'create_workspace',
  'create_workspace_collection',
  'update_workspace_collection',
  'create_character_kit',
  'open_character_kit',
  'update_character_kit',
  'attach_character_kit_references',
  'build_character_kit',
  'open_character_kit_rig',
  'apply_character_kit_preset',
  'track_character_kit_job',
  'create_video_editor_project',
  'open_video_editor_project',
  'add_video_editor_clips',
  'order_video_editor_clips',
  'trim_video_editor_clip',
  'add_video_editor_audio',
  'validate_video_editor_timeline',
  'export_video_editor',
  'track_video_editor_export',
  'attach_videoclip_alternative_song',
  'mount_videoclip_alternative_song',
] as const satisfies readonly AgentAction['type'][]

type MissingActionType = Exclude<AgentAction['type'], typeof AGENT_ACTION_TYPES[number]>
const allActionTypesAreDeclared: MissingActionType extends never ? true : never = true
void allActionTypesAreDeclared
